"""0001_initial_schema

Revision ID: 872211644880
Revises: 
Create Date: 2026-04-21 14:15:12.307887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '872211644880'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tba_event_key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('season_year', sa.SmallInteger(), nullable=False),
    sa.Column('perspective_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_season_year'), 'event', ['season_year'], unique=False)
    op.create_index(op.f('ix_event_tba_event_key'), 'event', ['tba_event_key'], unique=True)
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.SmallInteger(), nullable=False),
    sa.Column('team_name', sa.String(length=120), nullable=True),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_prov', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('rookie_year', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_team_team_number'), 'team', ['team_number'], unique=True)
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tba_match_key', sa.String(length=30), nullable=False),
    sa.Column('match_type', sa.String(length=15), nullable=False),
    sa.Column('match_number', sa.SmallInteger(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('video_s3_key', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("match_type in ('qualification', 'semifinal', 'final')", name='ck_match_match_type'),
    sa.CheckConstraint("processing_status in ('pending', 'processing', 'complete', 'failed')", name='ck_match_processing_status'),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index('idx_match_event_schedule', 'match', ['event_id', 'match_type', 'match_number'], unique=False)
    op.create_index('idx_match_processing_status', 'match', ['processing_status'], unique=False, postgresql_where=sa.text("processing_status != 'complete'"))
    op.create_index(op.f('ix_match_tba_match_key'), 'match', ['tba_match_key'], unique=True)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role in ('SCOUT', 'COACH', 'TEAM_ADMIN', 'SYSTEM_ADMIN')", name='ck_user_role'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_team_id'), 'user', ['team_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('alliance',
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=4), nullable=False),
    sa.Column('total_score', sa.SmallInteger(), nullable=True),
    sa.Column('rp_earned', sa.SmallInteger(), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.CheckConstraint("color in ('red', 'blue')", name='ck_alliance_color'),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alliance_id'),
    sa.UniqueConstraint('match_id', 'color', name='uq_alliance_match_color')
    )
    op.create_index(op.f('ix_alliance_match_id'), 'alliance', ['match_id'], unique=False)
    op.create_table('scouting_observation',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('scout_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_scouting_observation_rating'),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scout_id'], ['user.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_index('idx_scouting_observation_team_match', 'scouting_observation', ['team_id', 'match_id'], unique=False)
    op.create_index(op.f('ix_scouting_observation_scout_id'), 'scouting_observation', ['scout_id'], unique=False)
    op.create_table('sync_log',
    sa.Column('sync_id', sa.BigInteger(), nullable=False),
    sa.Column('sync_type', sa.String(length=30), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sync_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('sync_id')
    )
    op.create_index('idx_sync_log_timestamp_desc', 'sync_log', [sa.text('sync_timestamp DESC')], unique=False)
    op.create_index('idx_sync_log_type_resource', 'sync_log', ['sync_type', 'resource_id'], unique=False)
    op.create_table('robot_performance',
    sa.Column('perf_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('alliance_position', sa.SmallInteger(), nullable=False),
    sa.Column('track_id', sa.SmallInteger(), nullable=True),
    sa.Column('auto_score', sa.SmallInteger(), nullable=False),
    sa.Column('teleop_score', sa.SmallInteger(), nullable=False),
    sa.Column('endgame_score', sa.SmallInteger(), nullable=False),
    sa.Column('total_score_contribution', sa.SmallInteger(), sa.Computed('auto_score + teleop_score + endgame_score', persisted=True), nullable=False),
    sa.Column('fouls_drawn', sa.SmallInteger(), nullable=False),
    sa.Column('fouls_committed', sa.SmallInteger(), nullable=False),
    sa.Column('no_show', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('alliance_position in (1, 2, 3)', name='ck_robot_performance_alliance_position'),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.alliance_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('perf_id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_robot_performance_match_team')
    )
    op.create_index('idx_robot_performance_team_match', 'robot_performance', ['team_id', 'match_id'], unique=False)
    op.create_index(op.f('ix_robot_performance_alliance_id'), 'robot_performance', ['alliance_id'], unique=False)
    op.create_index(op.f('ix_robot_performance_match_id'), 'robot_performance', ['match_id'], unique=False)
    op.create_index(op.f('ix_robot_performance_team_id'), 'robot_performance', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robot_performance_team_id'), table_name='robot_performance')
    op.drop_index(op.f('ix_robot_performance_match_id'), table_name='robot_performance')
    op.drop_index(op.f('ix_robot_performance_alliance_id'), table_name='robot_performance')
    op.drop_index('idx_robot_performance_team_match', table_name='robot_performance')
    op.drop_table('robot_performance')
    op.drop_index('idx_sync_log_type_resource', table_name='sync_log')
    op.drop_index('idx_sync_log_timestamp_desc', table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_scouting_observation_scout_id'), table_name='scouting_observation')
    op.drop_index('idx_scouting_observation_team_match', table_name='scouting_observation')
    op.drop_table('scouting_observation')
    op.drop_index(op.f('ix_alliance_match_id'), table_name='alliance')
    op.drop_table('alliance')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_team_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_match_tba_match_key'), table_name='match')
    op.drop_index('idx_match_processing_status', table_name='match', postgresql_where=sa.text("processing_status != 'complete'"))
    op.drop_index('idx_match_event_schedule', table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_team_team_number'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_event_tba_event_key'), table_name='event')
    op.drop_index(op.f('ix_event_season_year'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
