"""Add UserAlliance table

Revision ID: c2d3e4f5g6h7
Revises: b1e2f3a4c5d6
Create Date: 2026-04-27 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = 'c2d3e4f5g6h7'
down_revision = 'b1e2f3a4c5d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_alliance',
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('red_teams', sa.String(length=255), nullable=False),
    sa.Column('blue_teams', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now()),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('alliance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_alliance')
    # ### end Alembic commands ###
